name: API Tests

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login -u "${{ secrets.DOCKERHUB_PASSWORD }}" -p "${{ secrets.DOCKERHUB_USERNAME }}"

   - name: Build Docker Image
      run: docker build -t talevskam/api-tests:latest .

    - name: Push Docker Image
      run: docker push talevskam/api-tests:latest
